platform :ios, "8.0"
use_frameworks!

target '2048X AI' do

# Utility
pod 'Loggerithm', :configurations => ['Debug'], :git => 'https://github.com/honghaoz/Loggerithm.git'
# pod 'ChouTi', :git => 'https://github.com/honghaoz/ChouTi.git'

# Analytics
pod 'Google/Analytics'

end

target '2048 SolverTests' do

end

